### PR TITLE
Added decision tree... probably should split train/test differently

### PR DESCRIPTION
**Pull request by kesshijordan**

### CODE REVIEW

**Comment by akeshavan** [comment]
@kesshijordan 

> WHOOPS... I just realized that I chose my training/testing in order... since these are ordered sequentially... there's a bias... should probably choose them randomly :( Megan: how did you choose?

What do you mean by this? Why does the order matter when training and testing?

**Comment by kesshijordan** [comment]
We are training before they have practiced... All the training is the early phase

On May 25, 2016, at 7:44 PM, Anisha Keshavan <notifications@github.com<mailto:notifications@github.com>> wrote:

WHOOPS... I just realized that I chose my training/testing in order... since these are ordered sequentially... there's a bias... should probably choose them randomly :( Megan: how did you choose?

What do you mean by this? Why does the order matter when training and testing?

**Comment by akeshavan** [comment]
ah ok, I did a KFold cross-validation, should take care of that, no?

**Comment by kesshijordan** [comment]
I didn't

On May 25, 2016, at 8:06 PM, Anisha Keshavan <notifications@github.com<mailto:notifications@github.com>> wrote:

ah ok, I did a KFold cross-validation, should take care of that, no?

**Pull request merged**
